[package]
name = "weather-cli-app"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
